//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace RapportFraStedet.AddressService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IAddressService", Namespace="http://tempuri.org/")]
    public partial class AddressService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetStreetsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAddressesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAddressOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AddressService() {
            this.Url = global::RapportFraStedet.Properties.Settings.Default.RapportFraStedet_AddressService_AddressService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetStreetsCompletedEventHandler GetStreetsCompleted;
        
        /// <remarks/>
        public event GetAddressesCompletedEventHandler GetAddressesCompleted;
        
        /// <remarks/>
        public event GetAddressCompletedEventHandler GetAddressCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAddressService/GetStreets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/RapportFraStedet.Models")]
        public StreetModel[] GetStreets() {
            object[] results = this.Invoke("GetStreets", new object[0]);
            return ((StreetModel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStreetsAsync() {
            this.GetStreetsAsync(null);
        }
        
        /// <remarks/>
        public void GetStreetsAsync(object userState) {
            if ((this.GetStreetsOperationCompleted == null)) {
                this.GetStreetsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStreetsOperationCompleted);
            }
            this.InvokeAsync("GetStreets", new object[0], this.GetStreetsOperationCompleted, userState);
        }
        
        private void OnGetStreetsOperationCompleted(object arg) {
            if ((this.GetStreetsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStreetsCompleted(this, new GetStreetsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAddressService/GetAddresses", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/RapportFraStedet.Models")]
        public AddressModel[] GetAddresses(int streetId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool streetIdSpecified) {
            object[] results = this.Invoke("GetAddresses", new object[] {
                        streetId,
                        streetIdSpecified});
            return ((AddressModel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAddressesAsync(int streetId, bool streetIdSpecified) {
            this.GetAddressesAsync(streetId, streetIdSpecified, null);
        }
        
        /// <remarks/>
        public void GetAddressesAsync(int streetId, bool streetIdSpecified, object userState) {
            if ((this.GetAddressesOperationCompleted == null)) {
                this.GetAddressesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAddressesOperationCompleted);
            }
            this.InvokeAsync("GetAddresses", new object[] {
                        streetId,
                        streetIdSpecified}, this.GetAddressesOperationCompleted, userState);
        }
        
        private void OnGetAddressesOperationCompleted(object arg) {
            if ((this.GetAddressesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAddressesCompleted(this, new GetAddressesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAddressService/GetAddress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AddressModel GetAddress(int streetId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool streetIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name) {
            object[] results = this.Invoke("GetAddress", new object[] {
                        streetId,
                        streetIdSpecified,
                        name});
            return ((AddressModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetAddressAsync(int streetId, bool streetIdSpecified, string name) {
            this.GetAddressAsync(streetId, streetIdSpecified, name, null);
        }
        
        /// <remarks/>
        public void GetAddressAsync(int streetId, bool streetIdSpecified, string name, object userState) {
            if ((this.GetAddressOperationCompleted == null)) {
                this.GetAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAddressOperationCompleted);
            }
            this.InvokeAsync("GetAddress", new object[] {
                        streetId,
                        streetIdSpecified,
                        name}, this.GetAddressOperationCompleted, userState);
        }
        
        private void OnGetAddressOperationCompleted(object arg) {
            if ((this.GetAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAddressCompleted(this, new GetAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RapportFraStedet.Models")]
    public partial class StreetModel {
        
        private string nameField;
        
        private int streetIdField;
        
        private bool streetIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int StreetId {
            get {
                return this.streetIdField;
            }
            set {
                this.streetIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StreetIdSpecified {
            get {
                return this.streetIdFieldSpecified;
            }
            set {
                this.streetIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RapportFraStedet.Models")]
    public partial class AddressModel {
        
        private string nameField;
        
        private string sRSField;
        
        private int streetIdField;
        
        private bool streetIdFieldSpecified;
        
        private double xField;
        
        private bool xFieldSpecified;
        
        private double yField;
        
        private bool yFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SRS {
            get {
                return this.sRSField;
            }
            set {
                this.sRSField = value;
            }
        }
        
        /// <remarks/>
        public int StreetId {
            get {
                return this.streetIdField;
            }
            set {
                this.streetIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StreetIdSpecified {
            get {
                return this.streetIdFieldSpecified;
            }
            set {
                this.streetIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XSpecified {
            get {
                return this.xFieldSpecified;
            }
            set {
                this.xFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YSpecified {
            get {
                return this.yFieldSpecified;
            }
            set {
                this.yFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetStreetsCompletedEventHandler(object sender, GetStreetsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStreetsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStreetsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StreetModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StreetModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAddressesCompletedEventHandler(object sender, GetAddressesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAddressesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAddressesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddressModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddressModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAddressCompletedEventHandler(object sender, GetAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddressModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddressModel)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591