//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapportFraStedet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public Field()
        {
            this.Permissions = new HashSet<Permission>();
            this.Selections = new HashSet<Selection>();
        }
    
        public int FieldId { get; set; }
        public string Name { get; set; }
        public int FormId { get; set; }
        public int FieldTypeId { get; set; }
        public int FieldOrder { get; set; }
        public bool Required { get; set; }
        public string FieldColumn { get; set; }
        public string Data { get; set; }
    
        public virtual FieldType FieldType { get; set; }
        public virtual Form Form { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
        public virtual ICollection<Selection> Selections { get; set; }
    }
}
