//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapportFraStedet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public Form()
        {
            this.Fields = new HashSet<Field>();
            this.Groups = new HashSet<Group>();
        }
    
        public int FormId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string ResourceName { get; set; }
        public string ClassName { get; set; }
        public string UploadPhysicalPath { get; set; }
        public string UploadVirtualPath { get; set; }
        public string ViewEmailToSenderOnCreate { get; set; }
        public string ViewEmailToReceiverOnCreate { get; set; }
        public string ViewEmailToSenderOnEdit { get; set; }
        public string ViewEmailToReceiverOnEdit { get; set; }
        public string ViewEmailToSenderOnDelete { get; set; }
        public string ViewEmailToReceiverOnDelete { get; set; }
        public string SRS { get; set; }
    
        public virtual ICollection<Field> Fields { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
    }
}
