//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapportFraStedet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int PermissionId { get; set; }
        public int FieldId { get; set; }
        public int ViewId { get; set; }
        public int PermissionTypeId { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual PermissionType PermissionType { get; set; }
        public virtual View View { get; set; }
    }
}
