//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapportFraStedet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewType
    {
        public ViewType()
        {
            this.Views = new HashSet<View>();
        }
    
        public int ViewTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<View> Views { get; set; }
    }
}
